version: "3.7"
services:
  plex:
    container_name: plexdev
    image: jeffwinn/plex-transcode-interceptor:latest
    restart: unless-stopped
    
    ports:
      - "1900:1900/udp"
      - "3005:3005/udp"
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
      - "8324:8324/tcp"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Detroit
      - PLEX_CLAIM=${PLEX_CLAIM}

    volumes:
      - ${USERPROFILE}/.plex/config:/config
      - ${USERPROFILE}/.plex/transcode:/transcode
      - ${USERPROFILE}/videos:/data/movies